knp_snappy:
    pdf:
        enabled:    true
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:
            enable-smart-shrinking: true
            no-outline: true
            page-size: Letter
            encoding: UTF-8
            margin-top: 15mm
            margin-bottom: 30mm
            margin-left: 20mm
            margin-right: 20mm
            footer-center: "Page [page]"
    image:
        enabled:    true
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\""
        options:    []